### PR TITLE
Adapter

### PR DESCRIPTION
**Pull request by ggarber**

### CODE REVIEW

**Comment by aullman** [comment]
Should we be using the npm version of adapter.js? https://www.npmjs.com/package/webrtc-adapter

**Comment by voltrevo** [comment]
As discussed on slack, this is done this way so it can include custom changes to adapterjs, but let's prefer the [workaround for separating constraints](https://github.com/opentok/webrtc-js/pull/2082), or better yet this [fix for adapterjs](https://github.com/webrtc/adapter/issues/408).

**Comment by ggarber** [comment]
Yes @aullman.  But we had to make 3 patches for adapter.js for Edge support (now merged in the repo but not yet included in the official npm package) + there is an open issue with the way we use gUM constrains being incompatible with adapter.js.

At this point these are the options we have IMO:
1. We wait until they change the way they manage gUM constrains and they generate a new version of adapter.js.
2. We deploy our custom adapter version until 1 happens.
3. We change the way we configure constraints and we use the the adapter.js version in github (not the one in npm because it doesn't have all the patches).

I'm in favor on doing 2 and then 1 when they are ready (my estimation is at least 1 month).    But let me know how do you prefer to proceed (@aiham @voltrevo @aullman)

**Comment by voltrevo** [comment]
@ggarber I'd have a chat with @aiham about the constraint changes that are landing soon. I think Firefox stopped respecting the advanced constraints anyway. If we still need adapter changes beyond what's been merged into the official version, then I'd still use npm for our fork via a github link in package.json like this: https://github.com/opentok/webrtc-js/blob/1d547e5/package.json#L96.

**Comment by aiham** [comment]
@voltrevo @aullman The changes to advanced constraints will be released in opentok.js 2.11. Should we still include adapter from npm to support current versions of Edge or close this ticket and wait for the Windows 10 Creator's Update: https://blogs.windows.com/msedgedev/2017/01/31/introducing-webrtc-microsoft-edge/#rBsFtMMUxEXx92v3.97

**Comment by aullman** [comment]
Closing this. We have actually included Adapter.js in opentok now.

**Pull request closed without merging**
