### PR TITLE
OPENTOK-47128 Fix npm build by removing git:// dependency

### PR DESCRIPTION
**Pull request by maikthomas**
#### What is this PR doing?
npm install was broken by git:// protocol used in dependency. 
I changed it to https:// in this repo
https://github.com/maikthomas/opentok-editor/commit/e572ab56c5353378bb14ef90f08b6a3d8958b3be
and then used that commit for our opentok-editor dependency in meet.

#### How should this be manually tested?
- Checkout locally and run `npm install`
- ensure it works

#### What are the relevant tickets?
OPENTOK-47128

### CODE REVIEW

**Review by v-kpheng — APPROVED** [review]
LGTM! 💪 🚀 

That said, how you do feel about submitting a patch upstream as well?  Please advise.  Thanks! 🙏

**Review by michaelwhittemore — APPROVED** [review]
lgtm

**Comment by maikthomas** [comment]
@v-kpheng do you mean open a PR to https://github.com/aullman/opentok-editor ?

**Comment by v-kpheng** [comment]
> @v-kpheng do you mean open a PR to https://github.com/aullman/opentok-editor ?

yes, please and thank you.

**Pull request merged**
