### PR TITLE
OPENTOK-45007 add e2ee to meet

### PR DESCRIPTION
**Pull request by maikthomas**
#### What is this PR doing?
Add E2EE option to meet

#### How should this be manually tested?
Run locally
- Check regular non e2ee works as before
- in landing page, select advanced, then e2ee and enter a passphrase
- open more tabs
- ensure entering with same passphrase allows you to see media
- ensure entering different or no passphrase does not allow you to see media from first tab
- enter room directly with url ending in e2ee=<yourpassphrase> and ensure that works too

#### What are the relevant tickets?

OPENTOK-45007

### CODE REVIEW

**Review by ggoldens — APPROVED** [review]
LGTM

**Review by ggoldens — APPROVED** [review]
LGTM (again)

**Review by albertoacn — COMMENTED** [review]
Tested!
With different pass-phrases in different tabs, there is not media flowing.
However, if one of the tabs is set to `e2ee=` and the others with their own pass-phrases, then the one with no passphrase will receive the encrypted media (i.e. unintelligible content).
Is this expected?

**Comment by albertoacn** [comment]
> Tested! With different pass-phrases in different tabs, there is not media flowing. However, if one of the tabs is set to `e2ee=` and the others with their own pass-phrases, then the one with no passphrase will receive the encrypted media (i.e. unintelligible content). Is this expected?

After discussion with @maikthomas , this is expected since `e2ee=` won't attempt to decrypt and just consume the encrypted media, and when a wrong passphrase is used this will fail to decrypt so no media is consumed.

**Review by albertoacn — APPROVED** [review]

**Pull request merged**
