### PR TITLE
OPENTOK-48117: Add support for virtual backgrounds

### PR DESCRIPTION
**Pull request by v-kpheng**
#### What is this PR doing?
Adds support for static virtual backgrounds

#### How should this be manually tested?

Click on the magic wand, to bring up a menu of cool backgrounds
image

Cycle through all of them.

That's it!

image

#### What are the relevant tickets?
https://jira.vonage.com/browse/OPENTOK-48117

### CODE REVIEW

**Review by maikthomas — COMMENTED** [review]
Code looks good, howeverI  tried out an alternative approach to make the UI a bit better, using the image itself as the thumbnail for the filter picker: 
I can send you my diff, but it's pretty much just adding another branch to the if at line 50, and extracting the bgUrl as you do below, and moving the image object up (or out of the file)
image

**Comment by maikthomas** [comment]
Here's the diff + newfile incase you just want to apply it

```diff
diff --git a/src/js/filter-picker.js b/src/js/filter-picker.js
index 186a2e3..262281d 100644
--- a/src/js/filter-picker.js
+++ b/src/js/filter-picker.js
@@ -4,6 +4,7 @@ const filterPickerHTML = require('../templates/filter-picker.html');
 require('../css/filter-picker.css');
 const filterous = require('filterous/lib/instaFilters');
 const filterousFilters = require('./filterous-filters');
+const backgroundImages = require('./background-images');

 function FilterPickerDirective() {
   function link(scope, element) {
@@ -46,6 +47,11 @@ function FilterPickerDirective() {
                   const tmpCtx = tmpCanvas.getContext('2d');
                   tmpCtx.putImageData(filteredImgData, 0, 0);
                   scope.filterImages[filter] = `${tmpCanvas.toDataURL('image/png')}`;
+                } else if (/^BG: [\s-\S]*/.test(filter)) {
+                  const [, image] = filter.match(/^BG: (.+)$/);
+                  const filename = backgroundImages[image];
+                  const backgroundImgUrl = `/images/${filename}`;
+                  scope.filterImages[filter] = backgroundImgUrl;
                 } else {
                   scope.filterImages[filter] = `${canvas.toDataURL('image/png')}`;
                 }
@@ -69,17 +75,8 @@ function FilterPickerDirective() {
         {
           regex: /^BG:/,
           config: () => {
-            const images = {
-              'Enterprise Bridge': 'enterprise-bridge.jpeg',
-              Beach: 'beach.jpg',
-              Simpsons: 'simpsons-couch.jpg',
-              Mountains: 'mountains.jpg',
-              Podium: 'podium.jpg',
-              "Ryu's Stage": 'ryu-stage.gif',
-            };
-
             const [, image] = filter.match(/^BG: (.+)$/);
-            const filename = images[image];
+            const filename = backgroundImages[image];
             const backgroundImgUrl = `/images/${filename}`;

             return {
```

plus newfile: backgroundImages.js
```js
const backgroundImages = {
  'Enterprise Bridge': 'enterprise-bridge.jpeg',
  Beach: 'beach.jpg',
  Simpsons: 'simpsons-couch.jpg',
  Mountains: 'mountains.jpg',
  Podium: 'podium.jpg',
  "Ryu's Stage": 'ryu-stage.gif',
};
module.exports = backgroundImages;

```

**Comment by v-kpheng** [comment]
> Code looks good, howeverI tried out an alternative approach to make the UI a bit better, using the image itself as the thumbnail for the filter picker: I can send you my diff, but it's pretty much just adding another branch to the if at line 50, and extracting the bgUrl as you do below, and moving the image object up (or out of the file) image

That is pretty cool :-)
I'll make some changes.  Thanks, man 🙏

**Comment by cpettet** [comment]
Tested with all backgrounds and works as-expected.

Screen Shot 2022-07-12 at 12 46 43 PM

**Pull request merged**
