### PR TITLE
OPENTOK-43733: Removed logging used to test for excessive RTT values

### PR DESCRIPTION
**Pull request by v-kpheng**
#### What is this PR doing?
Reverts https://github.com/opentok/opentok-meet/pull/130, basically

#### How should this be manually tested?
Make sure pub/sub still works

#### What are the relevant tickets?
https://jira.vonage.com/browse/OPENTOK-43733

### CODE REVIEW

**Review by prabhuvashwin — APPROVED** [review]
LGTM

**Comment by prabhuvashwin** [comment]
It looks like there is a build error -> https://app.travis-ci.com/github/opentok/opentok-meet/jobs/539276961

**Comment by v-kpheng** [comment]
> It looks like there is a build error -> https://app.travis-ci.com/github/opentok/opentok-meet/jobs/539276961

@prabhuvashwin , yeah, CI is broken and has been for sometime :-(

**Comment by prabhuvashwin** [comment]
> > It looks like there is a build error -> https://app.travis-ci.com/github/opentok/opentok-meet/jobs/539276961
> 
> @prabhuvashwin , yeah, CI is broken and has been for sometime :-(

Then we can't merge right?

**Comment by v-kpheng** [comment]
> > > It looks like there is a build error -> https://app.travis-ci.com/github/opentok/opentok-meet/jobs/539276961
> > 
> > 
> > @prabhuvashwin , yeah, CI is broken and has been for sometime :-(
> 
> Then we can't merge right?

Yep, we can.  Force merge ;-)

**Review by ggoldens — APPROVED** [review]
LGTM

**Review by ggoldens — APPROVED** [review]
Tested, LGTM.

**Pull request merged**
